framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            async: 'doctrine://default?auto_setup=1'
        routing:
            'App\Message\OrderNotificationMessage': async
