  services:
    database:
      image: postgres:15
      container_name: orders_db
      restart: always
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
        timeout: 5s
        retries: 5
        start_period: 60s
      volumes:
        - database_data:/var/lib/postgresql/data:rw
    mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
        - "8025:8025"   # веб-интерфейс для просмотра писем
        - "1025:1025"   # SMTP для отправки писем
  volumes:
    database_data:
